# Generated by Django 3.1.2 on 2021-01-09 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('User', '0010_auto_20210109_1242'),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budnum', models.CharField(max_length=50, verbose_name='楼号')),
            ],
            options={
                'verbose_name': '楼号',
            },
        ),
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floornum', models.CharField(max_length=20, verbose_name='楼层号')),
                ('budid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floor', to='life.building', verbose_name='楼号')),
            ],
            options={
                'verbose_name': '层',
                'verbose_name_plural': 'floors',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomnum', models.CharField(max_length=20, verbose_name='房间号')),
                ('status', models.CharField(max_length=20, verbose_name='状态')),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room', to='life.floor', verbose_name='层')),
            ],
            options={
                'verbose_name': '房间',
                'verbose_name_plural': 'Rooms',
            },
        ),
        migrations.CreateModel(
            name='TaskRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=50, verbose_name='原因')),
                ('flag', models.CharField(max_length=20, verbose_name='是否归寝')),
                ('createdtime', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('lastmodifytime', models.DateTimeField(verbose_name='最后修改时间')),
                ('buildingid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taskbuilding', to='life.building', verbose_name='楼id')),
                ('managerid', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='taskrecord', to='User.user', verbose_name='销假人')),
                ('objstuid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taskedstu', to='User.user', verbose_name='被执行者')),
                ('workerid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taskworker', to='User.user', verbose_name='执行者')),
            ],
            options={
                'verbose_name': '查寝记录',
            },
        ),
        migrations.CreateModel(
            name='StuInRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50, verbose_name='寝室状态(是否被查)')),
                ('roomid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stuinroom', to='life.room', verbose_name='房间id')),
                ('stuid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stuinroom', to='User.user', verbose_name='学生')),
            ],
            options={
                'verbose_name': '寝室信息',
            },
        ),
        migrations.CreateModel(
            name='RoomHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdtime', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('managerid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roomhistory', to='User.user', verbose_name='查寝人')),
                ('roomid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roomhistory', to='life.room', verbose_name='房间号')),
            ],
            options={
                'verbose_name': '寝室被查记录',
            },
        ),
    ]
