# Generated by Django 3.1.2 on 2020-10-30 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('0', '草稿'), ('1', '刚刚提交'), ('2', '班主任审核通过'), ('3', '上级通过')], default='0', max_length=20, verbose_name='状态')),
                ('contact_info', models.CharField(max_length=20, verbose_name='联系信息')),
                ('ask_type', models.CharField(choices=[('out', '外出'), ('leave', '事假'), ('other', '其他')], default='out', max_length=20, verbose_name='状态')),
                ('reason', models.CharField(max_length=50, verbose_name='理由')),
                ('place', models.CharField(max_length=50, verbose_name='地点')),
                ('ask_state', models.CharField(max_length=2, verbose_name='请假状态')),
                ('start_time', models.TimeField(verbose_name='开始时间')),
                ('end_time', models.TimeField(verbose_name='结束时间')),
                ('created_time', models.TimeField(verbose_name='创建时间')),
                ('modify_time', models.TimeField(verbose_name='修改时间')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.user', verbose_name='用户id')),
            ],
            options={
                'verbose_name': '请假条',
                'verbose_name_plural': '请假条',
            },
        ),
        migrations.CreateModel(
            name='Audit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(verbose_name='等级')),
                ('note', models.CharField(max_length=20, verbose_name='备注')),
                ('created_time', models.TimeField(verbose_name='创建时间')),
                ('modify_time', models.TimeField(verbose_name='修改时间')),
                ('ask_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ask.ask', verbose_name='请假单id')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.user', verbose_name='用户id')),
            ],
            options={
                'verbose_name': '审核情况表',
                'verbose_name_plural': '审核情况表',
            },
        ),
    ]
