# Generated by Django 3.1.3 on 2020-12-19 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('User', '0009_usermood_star_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('0', '草稿'), ('1', '班主任审核'), ('2', '院领导审核'), ('3', '通过'), ('4', '不通过')], default='0', max_length=4, verbose_name='审核状态')),
                ('contact_info', models.CharField(max_length=20, verbose_name='联系信息')),
                ('ask_type', models.CharField(choices=[('0', '外出'), ('1', '事假'), ('2', '其他')], default='1', max_length=20, verbose_name='状态')),
                ('reason', models.CharField(max_length=50, verbose_name='理由')),
                ('place', models.CharField(max_length=50, verbose_name='地点')),
                ('ask_state', models.CharField(choices=[('1', '完成'), ('0', '未完成')], default='0', max_length=5, verbose_name='是否完成')),
                ('start_time', models.DateTimeField(verbose_name='开始时间')),
                ('end_time', models.DateTimeField(verbose_name='结束时间')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('modify_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('grade_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='User.grade', verbose_name='班级')),
                ('pass_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pass_id', to='User.user', verbose_name='审批老师的id1')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_id', to='User.user', verbose_name='用户id')),
            ],
            options={
                'verbose_name': '请假条',
                'verbose_name_plural': '请假条',
            },
        ),
        migrations.CreateModel(
            name='Audit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('0', '草稿'), ('1', '班主任审核'), ('2', '院领导审核'), ('3', '通过'), ('4', '不通过')], max_length=4, verbose_name='审核状态')),
                ('explain', models.CharField(max_length=20, verbose_name='审核说明')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('modify_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('ask_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Ask.ask', verbose_name='请假单id')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.user', verbose_name='用户id')),
            ],
            options={
                'verbose_name': '审核情况表',
                'verbose_name_plural': '审核情况表',
                'ordering': ['-created_time'],
            },
        ),
    ]
