# Generated by Django 3.1.2 on 2020-11-05 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ask', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ask',
            name='created_time',
            field=models.TimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='ask',
            name='modify_time',
            field=models.TimeField(auto_now=True, verbose_name='修改时间'),
        ),
    ]
