# Generated by Django 3.1.2 on 2020-11-07 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ask', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ask',
            name='ask_state',
            field=models.CharField(choices=[('1', '完成'), ('0', '未完成')], default='0', max_length=5, verbose_name='是否完成'),
        ),
        migrations.AlterField(
            model_name='ask',
            name='status',
            field=models.CharField(choices=[('0', '草稿'), ('1', '刚刚提交'), ('2', '班主任审核通过'), ('3', '上级通过')], default='0', max_length=20, verbose_name='审核状态'),
        ),
    ]
