# Generated by Django 3.1.3 on 2020-11-26 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
        ('Ask', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ask',
            name='grade_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='User.grade', verbose_name='班级'),
        ),
    ]
