# Generated by Django 3.1.2 on 2020-11-11 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ask', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ask',
            name='ask_type',
            field=models.CharField(choices=[('0', '外出'), ('1', '事假'), ('2', '其他')], default='1', max_length=20, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='ask',
            name='status',
            field=models.CharField(choices=[('0', '草稿'), ('1', '等待一级审核'), ('2', '等待二级审核'), ('3', '完成')], default='0', max_length=20, verbose_name='审核状态'),
        ),
    ]
