# Generated by Django 3.1.2 on 2020-11-16 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ask', '0002_auto_20201111_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audit',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='audit',
            name='modify_time',
            field=models.DateTimeField(auto_now=True, verbose_name='修改时间'),
        ),
    ]
