# Generated by Django 3.1.3 on 2020-12-14 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ask', '0004_auto_20201126_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ask',
            name='status',
            field=models.CharField(choices=[('0', '草稿'), ('1', '班主任审核'), ('2', '等待二级审核'), ('3', '完成'), ('4', '不通过')], default='0', max_length=4, verbose_name='审核状态'),
        ),
        migrations.AlterField(
            model_name='audit',
            name='status',
            field=models.CharField(choices=[('0', '草稿'), ('1', '班主任审核'), ('2', '等待二级审核'), ('3', '完成'), ('4', '不通过')], max_length=4, verbose_name='审核状态'),
        ),
    ]
