# Generated by Django 3.1.3 on 2020-12-14 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ask', '0005_auto_20201214_1217'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='audit',
            options={'ordering': ['-created_time'], 'verbose_name': '审核情况表', 'verbose_name_plural': '审核情况表'},
        ),
        migrations.AlterField(
            model_name='ask',
            name='status',
            field=models.CharField(choices=[('0', '草稿'), ('1', '班主任审核'), ('2', '院领导审核'), ('3', '通过'), ('4', '不通过')], default='0', max_length=4, verbose_name='审核状态'),
        ),
        migrations.AlterField(
            model_name='audit',
            name='status',
            field=models.CharField(choices=[('0', '草稿'), ('1', '班主任审核'), ('2', '院领导审核'), ('3', '通过'), ('4', '不通过')], max_length=4, verbose_name='审核状态'),
        ),
    ]
