# Generated by Django 3.1.3 on 2020-12-15 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Manage', '0002_auto_20201215_0823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typechild',
            name='par_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Manage.typepar', verbose_name='父表id'),
        ),
    ]
