# Generated by Django 3.1.3 on 2020-12-12 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_auto_20201126_1136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='token',
            name='wx_openid',
        ),
        migrations.CreateModel(
            name='Tpost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wx_openid', models.CharField(max_length=128, verbose_name='微信标识')),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='User.user')),
            ],
            options={
                'verbose_name': '第三方账户',
                'verbose_name_plural': '第三方账户',
                'db_table': '',
                'managed': True,
            },
        ),
    ]
