# Generated by Django 3.1.3 on 2020-12-17 21:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0008_usermood'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermood',
            name='star_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='创建日期'),
            preserve_default=False,
        ),
    ]
