# Generated by Django 3.1.2 on 2020-11-07 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Career', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='career',
            options={'ordering': ['id'], 'verbose_name': '就业信息表', 'verbose_name_plural': '就业信息表'},
        ),
    ]
