# Generated by Django 3.1.3 on 2020-12-15 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Manage', '0003_auto_20201215_0825'),
        ('Career', '0002_auto_20201215_0823'),
    ]

    operations = [
        migrations.AddField(
            model_name='career',
            name='classify',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Manage.typechild', verbose_name='分类'),
            preserve_default=False,
        ),
    ]
