# Generated by Django 3.1.2 on 2020-11-07 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Career', '0002_auto_20201107_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='career',
            name='release_time',
            field=models.DateTimeField(verbose_name='发布时间'),
        ),
    ]
