# Generated by Django 3.1.2 on 2020-11-07 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Career', '0003_auto_20201107_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='career',
            name='viewnum',
            field=models.IntegerField(default=0, verbose_name='浏览数'),
        ),
    ]
