# Generated by Django 3.1.3 on 2021-01-26 23:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Manage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('note', models.CharField(max_length=300, verbose_name='介绍')),
                ('text', models.TextField(verbose_name='正文')),
                ('source', models.CharField(blank=True, max_length=100, null=True, verbose_name='地址')),
                ('viewnum', models.IntegerField(default=0, verbose_name='浏览数')),
                ('star_time', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('last_time', models.DateTimeField(auto_now=True, verbose_name='最后修改日期')),
                ('classify', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Manage.typechild', verbose_name='分类')),
            ],
            options={
                'verbose_name': '文章',
                'verbose_name_plural': '文章',
                'ordering': ['id'],
            },
        ),
    ]
