# Generated by Django 3.1.3 on 2020-12-15 08:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Career', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='career',
            options={'ordering': ['id'], 'verbose_name': '文章', 'verbose_name_plural': '文章'},
        ),
        migrations.RemoveField(
            model_name='career',
            name='release_time',
        ),
        migrations.AddField(
            model_name='career',
            name='last_time',
            field=models.DateTimeField(auto_now=True, verbose_name='最后修改日期'),
        ),
        migrations.AddField(
            model_name='career',
            name='star_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='创建日期'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='career',
            name='note',
            field=models.CharField(max_length=300, verbose_name='介绍'),
        ),
        migrations.AlterField(
            model_name='career',
            name='title',
            field=models.CharField(max_length=100, verbose_name='标题'),
        ),
    ]
