# Generated by Django 3.1.3 on 2020-12-15 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Career', '0003_career_classify'),
    ]

    operations = [
        migrations.AlterField(
            model_name='career',
            name='text',
            field=models.TextField(verbose_name='正文'),
        ),
    ]
