# Generated by Django 3.1.2 on 2020-10-30 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='学院名称')),
            ],
            options={
                'verbose_name': 'college',
                'verbose_name_plural': 'colleges',
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='班级名称')),
                ('college_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.college', verbose_name='学院id')),
            ],
            options={
                'verbose_name': '班级',
                'verbose_name_plural': '班级',
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('common', '普通'), ('amdin', '管理员')], default='common', max_length=20, verbose_name='权限')),
                ('message', models.CharField(max_length=50, verbose_name='描述')),
            ],
            options={
                'verbose_name': '权限',
                'verbose_name_plural': '权限',
            },
        ),
        migrations.CreateModel(
            name='TeacherInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fieldName', models.CharField(max_length=150)),
                ('teacher_extra_info', models.CharField(max_length=50, verbose_name='老师额外信息')),
            ],
            options={
                'verbose_name': '老师信息',
                'verbose_name_plural': '老师信息',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=20, verbose_name='用户名')),
                ('pass_word', models.CharField(max_length=20, verbose_name='用户密码')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='姓名')),
                ('tel', models.CharField(max_length=20, verbose_name='电话')),
                ('identity', models.CharField(choices=[('student', '学生'), ('teacher', '老师')], default='student', max_length=20, verbose_name='身份')),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='User.user')),
            ],
            options={
                'verbose_name': '用户信息',
                'verbose_name_plural': '用户信息',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UserForPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perm_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.permission')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.user')),
            ],
            options={
                'verbose_name': '用户权限表',
                'verbose_name_plural': '用户权限表',
            },
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=100)),
                ('wx_token', models.CharField(max_length=100)),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='User.user')),
            ],
            options={
                'verbose_name': '用户token',
                'verbose_name_plural': '用户token',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TeacherForGrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.grade')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.user')),
            ],
            options={
                'verbose_name': '教师班级关系',
                'verbose_name_plural': '教师班级关系',
            },
        ),
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=20, verbose_name='学号')),
                ('grade_id', models.CharField(max_length=20, verbose_name='班级号')),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='User.user', verbose_name='用户id')),
            ],
            options={
                'verbose_name': '学生信息',
                'verbose_name_plural': '学生信息',
                'db_table': '',
                'managed': True,
            },
        ),
    ]
