# Generated by Django 3.1.2 on 2020-10-30 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='college',
            options={'verbose_name': '分院', 'verbose_name_plural': '分院'},
        ),
    ]
