# Generated by Django 3.1.2 on 2020-11-05 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='token',
            old_name='wx_token',
            new_name='wx_openid',
        ),
    ]
