# Generated by Django 3.1.2 on 2020-11-16 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_auto_20201111_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='identity',
            field=models.CharField(choices=[('student', '学生'), ('teacher', '老师'), ('ld', '领导')], default='student', max_length=20, verbose_name='身份'),
        ),
    ]
