# Generated by Django 3.1.2 on 2020-10-30 15:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_auto_20201030_2311'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherinfo',
            name='user_id',
            field=models.OneToOneField(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='User.user', verbose_name='用户'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='grade_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='User.grade'),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='user_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='User.user', verbose_name='用户'),
        ),
    ]
