# Generated by Django 3.1.2 on 2020-11-07 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_auto_20201105_2128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacherinfo',
            name='fieldName',
        ),
        migrations.AlterField(
            model_name='grade',
            name='college_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.college', verbose_name='学院'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='name',
            field=models.CharField(max_length=20, verbose_name='班级号'),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='grade_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='User.grade', verbose_name='年级id'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='user_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='User.user', verbose_name='用户id'),
        ),
    ]
