# Generated by Django 3.1.3 on 2020-12-13 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_auto_20201213_0946'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tpost',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='tpost',
            name='wx_openid',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='微信标识'),
        ),
    ]
