# Generated by Django 3.1.3 on 2020-12-14 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0006_auto_20201213_0952'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentinfo',
            name='student_id',
        ),
    ]
