# Generated by Django 3.1.3 on 2020-12-17 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0007_remove_studentinfo_student_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mod_level', models.CharField(max_length=2, verbose_name='心情等级')),
                ('message', models.CharField(max_length=9999, verbose_name='想说的话')),
                ('Grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.grade', verbose_name='班级')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.user', verbose_name='学生用户')),
            ],
            options={
                'verbose_name': '心情监测表',
                'verbose_name_plural': '心情监测表',
            },
        ),
    ]
