# Generated by Django 3.1.2 on 2021-01-09 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0009_usermood_star_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='identity',
            field=models.CharField(choices=[('student', '学生'), ('teacher', '老师'), ('college', '院领导'), ('life', '生活部')], default='student', max_length=20, verbose_name='身份'),
        ),
    ]
