# Generated by Django 3.1.3 on 2021-01-26 23:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='权限名称')),
                ('per_type', models.CharField(default='0', max_length=150, verbose_name='类型')),
                ('description', models.CharField(blank=True, max_length=150, null=True, verbose_name='描述')),
            ],
            options={
                'verbose_name': '权限',
                'verbose_name_plural': '权限',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='职位')),
                ('ability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rolepermission', to='Permission.permission', verbose_name='操作权限')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roleuser', to='User.user', verbose_name='用户')),
            ],
            options={
                'verbose_name': '角色表',
                'verbose_name_plural': '角色表',
            },
        ),
        migrations.CreateModel(
            name='OperatePermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='操作')),
                ('per_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operatepermission', to='Permission.permission', verbose_name='权限')),
            ],
            options={
                'verbose_name': '操作权限记录',
                'verbose_name_plural': '操作权限记录',
            },
        ),
        migrations.CreateModel(
            name='ElementPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='名称')),
                ('per_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elementpermission', to='Permission.permission', verbose_name='权限')),
            ],
            options={
                'verbose_name': 'ElementPermission',
                'verbose_name_plural': '元素显示权限',
            },
        ),
        migrations.CreateModel(
            name='ApiPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200, verbose_name='地址')),
                ('method', models.CharField(choices=[('GET', 'get方法'), ('POST', 'post方法'), ('PUT', 'put方法'), ('DELETE', 'delete方法')], default='GET', max_length=50, verbose_name='请求方法')),
                ('per_id', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='apipermission', to='Permission.permission', verbose_name='权限')),
            ],
            options={
                'verbose_name': '接口权限记录',
                'verbose_name_plural': '接口权限记录',
            },
        ),
    ]
